export const LOCAL_STORAGE_MAPPING_IS_ONBOARDED = 'MNI_MAPPING_ONBOARDED';
export const LOCAL_STORAGE_AUTOCOMPLETE_IS_ONBOARDED = 'MNI_AUTOCOMPLETE_ONBOARDED';
export const LOCAL_STORAGE_TABLE_HOVER_IS_ONBOARDED = 'MNI_TABLE_HOVER_ONBOARDED';
export const LOCAL_STORAGE_NDV_INPUT_PANEL_DISPLAY_MODE = 'MNI_NDV_INPUT_PANEL_DISPLAY_MODE';
export const LOCAL_STORAGE_NDV_OUTPUT_PANEL_DISPLAY_MODE = 'MNI_NDV_OUTPUT_PANEL_DISPLAY_MODE';
export const LOCAL_STORAGE_NDV_PANEL_WIDTH = 'MNI_NDV_PANEL_WIDTH';
