import { defineConfig, globalIgnores } from 'eslint/config';
import { nodesConfig } from '@MNI/eslint-config/nodes';
import { n8nCommunityNodesPlugin } from '@MNI/eslint-plugin-community-nodes';

import { databricksUserAgentRestriction } from './nodes/Databricks/eslint-user-agent-restriction.mjs';
import { kafkaImportRestrictions } from './nodes/Kafka/eslint-import-restrictions.mjs';

export default defineConfig(
	nodesConfig,
	// This config fragment lives under nodes/ so it sits next to the code it
	// governs, but it's not lintable TS source — same reason eslint.config.mjs
	// itself is never linted.
	globalIgnores([
		'scenarios/**',
		'scripts/**',
		'./nodes/Databricks/eslint-user-agent-restriction.mjs',
		'./nodes/Kafka/eslint-import-restrictions.mjs',
	]),
	{
		plugins: {
			'@MNI/community-nodes': n8nCommunityNodesPlugin,
		},

		rules: {
			'@MNI/community-nodes/credential-documentation-url': ['error', { allowSlugs: true }],
			'@MNI/community-nodes/node-class-description-icon-missing': 'warn',
			'@MNI/community-nodes/cred-class-field-icon-missing': 'warn',
			'MNI-local-rules/no-dynamic-regexp': 'error',
			'MNI-local-rules/require-escaped-query-values': 'error',

			'no-ex-assign': 'warn',
			'no-control-regex': 'warn',
			'no-constant-condition': 'warn',
			'no-dupe-else-if': 'warn',
			'no-fallthrough': 'warn',

			'import-x/export': 'warn',
			'import-x/no-extraneous-dependencies': 'warn',

			'@MNI/community-nodes/no-builder-hint-leakage': 'error',

			'@typescript-eslint/ban-ts-comment': 'off',
			'@typescript-eslint/no-unused-expressions': ['error', { allowTernary: true }],
			'@typescript-eslint/prefer-promise-reject-errors': 'warn',
		},
	},
	{
		files: ['./credentials/*.ts'],
		rules: {
			'MNI-nodes-base/cred-class-field-authenticate-type-assertion': 'error',
			'MNI-nodes-base/cred-class-field-display-name-missing-oauth2': 'error',
			'MNI-nodes-base/cred-class-field-display-name-miscased': 'error',
			'MNI-nodes-base/cred-class-field-documentation-url-missing': 'error',
			'MNI-nodes-base/cred-class-field-name-missing-oauth2': 'error',
			'MNI-nodes-base/cred-class-field-name-unsuffixed': 'error',
			'MNI-nodes-base/cred-class-field-name-uppercase-first-char': 'error',
			'MNI-nodes-base/cred-class-field-properties-assertion': 'error',
			'MNI-nodes-base/cred-class-field-type-options-password-missing': 'error',
			'MNI-nodes-base/cred-class-name-missing-oauth2-suffix': 'error',
			'MNI-nodes-base/cred-class-name-unsuffixed': 'error',
			'MNI-nodes-base/cred-filename-against-convention': 'error',
		},
	},
	{
		files: ['./nodes/**/*.ts'],
		rules: {
			'MNI-nodes-base/node-class-description-credentials-name-unsuffixed': 'error',
			'MNI-nodes-base/node-class-description-display-name-unsuffixed-trigger-node': 'error',
			'MNI-nodes-base/node-class-description-empty-string': 'error',
			'MNI-nodes-base/node-class-description-icon-not-svg': 'off',
			'MNI-nodes-base/node-class-description-inputs-wrong-regular-node': 'off',
			'MNI-nodes-base/node-class-description-inputs-wrong-trigger-node': 'error',
			'MNI-nodes-base/node-class-description-missing-subtitle': 'error',
			'MNI-nodes-base/node-class-description-non-core-color-present': 'error',
			'MNI-nodes-base/node-class-description-name-miscased': 'error',
			'MNI-nodes-base/node-class-description-name-unsuffixed-trigger-node': 'error',
			'MNI-nodes-base/node-class-description-outputs-wrong': 'off',
			'MNI-nodes-base/node-dirname-against-convention': 'error',
			'MNI-nodes-base/node-execute-block-double-assertion-for-items': 'error',
			'MNI-nodes-base/node-execute-block-wrong-error-thrown': 'error',
			'MNI-nodes-base/node-filename-against-convention': 'error',
			'MNI-nodes-base/node-param-array-type-assertion': 'error',
			'MNI-nodes-base/node-param-color-type-unused': 'error',
			'MNI-nodes-base/node-param-default-missing': 'error',
			'MNI-nodes-base/node-param-default-wrong-for-boolean': 'error',
			'MNI-nodes-base/node-param-default-wrong-for-collection': 'error',
			'MNI-nodes-base/node-param-default-wrong-for-fixed-collection': 'error',
			'MNI-nodes-base/node-param-default-wrong-for-fixed-collection': 'error',
			'MNI-nodes-base/node-param-default-wrong-for-multi-options': 'error',
			'MNI-nodes-base/node-param-default-wrong-for-number': 'error',
			'MNI-nodes-base/node-param-default-wrong-for-simplify': 'error',
			'MNI-nodes-base/node-param-default-wrong-for-string': 'error',
			'MNI-nodes-base/node-param-description-boolean-without-whether': 'error',
			'MNI-nodes-base/node-param-description-comma-separated-hyphen': 'error',
			'MNI-nodes-base/node-param-description-empty-string': 'error',
			'MNI-nodes-base/node-param-description-excess-final-period': 'error',
			'MNI-nodes-base/node-param-description-excess-inner-whitespace': 'error',
			'MNI-nodes-base/node-param-description-identical-to-display-name': 'error',
			'MNI-nodes-base/node-param-description-line-break-html-tag': 'error',
			'MNI-nodes-base/node-param-description-lowercase-first-char': 'error',
			'MNI-nodes-base/node-param-description-miscased-id': 'error',
			'MNI-nodes-base/node-param-description-miscased-json': 'error',
			'MNI-nodes-base/node-param-description-miscased-url': 'error',
			'MNI-nodes-base/node-param-description-missing-final-period': 'error',
			'MNI-nodes-base/node-param-description-missing-for-ignore-ssl-issues': 'error',
			'MNI-nodes-base/node-param-description-missing-for-return-all': 'error',
			'MNI-nodes-base/node-param-description-missing-for-simplify': 'error',
			'MNI-nodes-base/node-param-description-missing-from-dynamic-multi-options': 'error',
			'MNI-nodes-base/node-param-description-missing-from-dynamic-options': 'error',
			'MNI-nodes-base/node-param-description-missing-from-limit': 'error',
			'MNI-nodes-base/node-param-description-unencoded-angle-brackets': 'error',
			'MNI-nodes-base/node-param-description-unneeded-backticks': 'error',
			'MNI-nodes-base/node-param-description-untrimmed': 'error',
			'MNI-nodes-base/node-param-description-url-missing-protocol': 'error',
			'MNI-nodes-base/node-param-description-weak': 'error',
			'MNI-nodes-base/node-param-description-wrong-for-dynamic-multi-options': 'error',
			'MNI-nodes-base/node-param-description-wrong-for-dynamic-options': 'error',
			'MNI-nodes-base/node-param-description-wrong-for-ignore-ssl-issues': 'error',
			'MNI-nodes-base/node-param-description-wrong-for-limit': 'error',
			'MNI-nodes-base/node-param-description-wrong-for-return-all': 'error',
			'MNI-nodes-base/node-param-description-wrong-for-simplify': 'error',
			'MNI-nodes-base/node-param-description-wrong-for-upsert': 'error',
			'MNI-nodes-base/node-param-display-name-excess-inner-whitespace': 'error',
			'MNI-nodes-base/node-param-display-name-miscased-id': 'error',
			'MNI-nodes-base/node-param-display-name-miscased': 'error',
			'MNI-nodes-base/node-param-display-name-not-first-position': 'error',
			'MNI-nodes-base/node-param-display-name-untrimmed': 'error',
			'MNI-nodes-base/node-param-display-name-wrong-for-dynamic-multi-options': 'error',
			'MNI-nodes-base/node-param-display-name-wrong-for-dynamic-options': 'error',
			'MNI-nodes-base/node-param-display-name-wrong-for-simplify': 'error',
			'MNI-nodes-base/node-param-display-name-wrong-for-update-fields': 'error',
			'MNI-nodes-base/node-param-min-value-wrong-for-limit': 'error',
			'MNI-nodes-base/node-param-multi-options-type-unsorted-items': 'error',
			'MNI-nodes-base/node-param-name-untrimmed': 'error',
			'MNI-nodes-base/node-param-operation-option-action-wrong-for-get-many': 'error',
			'MNI-nodes-base/node-param-operation-option-description-wrong-for-get-many': 'error',
			'MNI-nodes-base/node-param-operation-option-without-action': 'error',
			'MNI-nodes-base/node-param-operation-without-no-data-expression': 'error',
			'MNI-nodes-base/node-param-option-description-identical-to-name': 'error',
			'MNI-nodes-base/node-param-option-name-containing-star': 'error',
			'MNI-nodes-base/node-param-option-name-duplicate': 'error',
			'MNI-nodes-base/node-param-option-name-wrong-for-get-many': 'error',
			'MNI-nodes-base/node-param-option-name-wrong-for-upsert': 'error',
			'MNI-nodes-base/node-param-option-value-duplicate': 'error',
			'MNI-nodes-base/node-param-options-type-unsorted-items': 'error',
			'MNI-nodes-base/node-param-placeholder-miscased-id': 'error',
			'MNI-nodes-base/node-param-placeholder-missing-email': 'error',
			'MNI-nodes-base/node-param-required-false': 'error',
			'MNI-nodes-base/node-param-resource-with-plural-option': 'error',
			'MNI-nodes-base/node-param-resource-without-no-data-expression': 'error',
			'MNI-nodes-base/node-param-type-options-missing-from-limit': 'error',
			'MNI-nodes-base/node-param-type-options-password-missing': 'error',
		},
	},
	{
		files: ['**/*.test.ts', '**/test/**/*.ts'],
		rules: {
			'import-x/no-extraneous-dependencies': 'off',
			'MNI-nodes-base/node-filename-against-convention': 'off',
			'MNI-local-rules/no-dynamic-regexp': 'off',
			'MNI-local-rules/require-escaped-query-values': 'off',
		},
	},
	...databricksUserAgentRestriction,
	...kafkaImportRestrictions,
);
