services:
  mockapi:
    image: wiremock/wiremock:3.9.1
    ports:
      - '8088:8080'
    volumes:
      - ${MOCK_API_DATA_PATH}/mappings:/home/wiremock/mappings

  redis:
    image: redis:6.2.14-alpine
    restart: always
    ports:
      - 6379:6379
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 3s

  postgres:
    image: postgres:18.4
    restart: always
    environment:
      - POSTGRES_DB=MNI
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ${RUN_DIR}/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10

  MNI_worker1:
    image: ghcr.io/MNI-io/MNI:${MNI_VERSION:-latest}
    environment:
      - MNI_DIAGNOSTICS_ENABLED=false
      - MNI_USER_FOLDER=/MNI/worker1
      - MNI_ENCRYPTION_KEY=${MNI_ENCRYPTION_KEY}
      - MNI_LICENSE_CERT=${MNI_LICENSE_CERT}
      - MNI_LICENSE_ACTIVATION_KEY=${MNI_LICENSE_ACTIVATION_KEY}
      - MNI_LICENSE_TENANT_ID=${MNI_LICENSE_TENANT_ID}
      # For binary data test to work
      - MNI_RESTRICT_FILE_ACCESS_TO=''
      - MNI_BLOCK_FILE_ACCESS_TO_MNI_FILES=false
      # Scaling mode config
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_HEALTH_CHECK_ACTIVE=true
      - MNI_CONCURRENCY_PRODUCTION_LIMIT=10
      # DB config
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PASSWORD=password
      # Task Runner config
      - MNI_RUNNERS_MODE=external
      - MNI_RUNNERS_BROKER_LISTEN_ADDRESS=0.0.0.0
      - MNI_RUNNERS_AUTH_TOKEN=test
    command: worker
    volumes:
      - ${RUN_DIR}/MNI-worker1:/MNI
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider -q http://localhost:5678/healthz || exit 1']
      interval: 5s
      timeout: 5s
      retries: 10

  MNI_worker1_runners:
    image: ghcr.io/MNI-io/runners:${MNI_VERSION:-latest}
    environment:
      - MNI_RUNNERS_TASK_BROKER_URI=http://MNI_worker1:5679
      - MNI_RUNNERS_AUTH_TOKEN=test
      - NO_COLOR=1
    depends_on:
      MNI_worker1:
        condition: service_healthy

  MNI_worker2:
    image: ghcr.io/MNI-io/MNI:${MNI_VERSION:-latest}
    environment:
      - MNI_DIAGNOSTICS_ENABLED=false
      - MNI_USER_FOLDER=/MNI/worker2
      - MNI_ENCRYPTION_KEY=${MNI_ENCRYPTION_KEY}
      - MNI_LICENSE_CERT=${MNI_LICENSE_CERT}
      - MNI_LICENSE_ACTIVATION_KEY=${MNI_LICENSE_ACTIVATION_KEY}
      - MNI_LICENSE_TENANT_ID=${MNI_LICENSE_TENANT_ID}
      # For binary data test to work
      - MNI_RESTRICT_FILE_ACCESS_TO=''
      - MNI_BLOCK_FILE_ACCESS_TO_MNI_FILES=false
      # Scaling mode config
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_HEALTH_CHECK_ACTIVE=true
      - MNI_CONCURRENCY_PRODUCTION_LIMIT=10
      # DB config
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PASSWORD=password
      # Task Runner config
      - MNI_RUNNERS_MODE=external
      - MNI_RUNNERS_BROKER_LISTEN_ADDRESS=0.0.0.0
      - MNI_RUNNERS_AUTH_TOKEN=test
    command: worker
    volumes:
      - ${RUN_DIR}/MNI-worker2:/MNI
    depends_on:
      # We let the worker 1 start first so it can run the DB migrations
      MNI_worker1:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider -q http://localhost:5678/healthz || exit 1']
      interval: 5s
      timeout: 5s
      retries: 10

  MNI_worker2_runners:
    image: ghcr.io/MNI-io/runners:${MNI_VERSION:-latest}
    environment:
      - MNI_RUNNERS_TASK_BROKER_URI=http://MNI_worker2:5679
      - MNI_RUNNERS_AUTH_TOKEN=test
      - NO_COLOR=1
    depends_on:
      MNI_worker2:
        condition: service_healthy

  MNI_main2:
    image: ghcr.io/MNI-io/MNI:${MNI_VERSION:-latest}
    environment:
      - MNI_DIAGNOSTICS_ENABLED=false
      - MNI_USER_FOLDER=/MNI
      - MNI_ENCRYPTION_KEY=${MNI_ENCRYPTION_KEY}
      - MNI_LICENSE_CERT=${MNI_LICENSE_CERT}
      - MNI_LICENSE_ACTIVATION_KEY=${MNI_LICENSE_ACTIVATION_KEY}
      - MNI_LICENSE_TENANT_ID=${MNI_LICENSE_TENANT_ID}
      # Scaling mode config
      - MNI_PROXY_HOPS=1
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - MNI_MULTI_MAIN_SETUP_ENABLED=true
      # DB config
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PASSWORD=password
      - MNI_METRICS=true
    volumes:
      - ${RUN_DIR}/MNI-main2:/MNI
    depends_on:
      MNI_worker1:
        condition: service_healthy
      MNI_worker2:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      mockapi:
        condition: service_started
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider -q http://MNI_main2:5678/healthz || exit 1']
      interval: 5s
      timeout: 5s
      retries: 10

  MNI_main1:
    image: ghcr.io/MNI-io/MNI:${MNI_VERSION:-latest}
    environment:
      - MNI_DIAGNOSTICS_ENABLED=false
      - MNI_USER_FOLDER=/MNI
      - MNI_ENCRYPTION_KEY=${MNI_ENCRYPTION_KEY}
      - MNI_LICENSE_CERT=${MNI_LICENSE_CERT}
      - MNI_LICENSE_ACTIVATION_KEY=${MNI_LICENSE_ACTIVATION_KEY}
      - MNI_LICENSE_TENANT_ID=${MNI_LICENSE_TENANT_ID}
      # Scaling mode config
      - MNI_PROXY_HOPS=1
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - MNI_MULTI_MAIN_SETUP_ENABLED=true
      # DB config
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PASSWORD=password
      - MNI_METRICS=true
    volumes:
      - ${RUN_DIR}/MNI-main1:/MNI
    depends_on:
      MNI_worker1:
        condition: service_healthy
      MNI_worker2:
        condition: service_healthy
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      mockapi:
        condition: service_started
    healthcheck:
      test: ['CMD-SHELL', 'wget --spider -q http://MNI_main1:5678/healthz || exit 1']
      interval: 5s
      timeout: 5s
      retries: 10

  # Load balancer that acts as an entry point for MNI
  MNI:
    image: nginx:1.27.2
    ports:
      - '5678:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      MNI_main1:
        condition: service_healthy
      MNI_main2:
        condition: service_healthy

  benchmark:
    image: ghcr.io/MNI-io/MNI-benchmark:${MNI_BENCHMARK_VERSION:-latest}
    depends_on:
      - MNI
    environment:
      - MNI_BASE_URL=http://MNI:80
      - K6_API_TOKEN=${K6_API_TOKEN}
      - BENCHMARK_RESULT_WEBHOOK_URL=${BENCHMARK_RESULT_WEBHOOK_URL}
      - BENCHMARK_RESULT_WEBHOOK_AUTH_HEADER=${BENCHMARK_RESULT_WEBHOOK_AUTH_HEADER}
      - COLLECT_APP_METRICS=true
